services:
  - type: web
    name: scarlet-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: scarlet-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: BCRYPT_SALT_ROUNDS
        value: "12"
      - key: CORS_ORIGIN
        value: "https://scarletunlimited.net"
      - key: API_RATE_LIMIT
        value: "100"
      - key: MAX_FILE_SIZE
        value: "5242880"

databases:
  - name: scarlet-mongodb
    databaseName: scarlet_production
    user: scarlet_user
    plan: starter
