#!/bin/bash
# Script to check SMS/OTP logs on DigitalOcean server via SSH

echo "🔍 SMS/OTP Log Check Commands for DigitalOcean Server"
echo ""
echo "SSH into your server first:"
echo "   ssh root@139.59.114.43"
echo ""
echo "Then run these commands:"
echo ""
echo "1️⃣ Check recent OTP/SMS related logs:"
echo "   pm2 logs | grep -iE 'otp|sms|password.*reset' | tail -100"
echo ""
echo "2️⃣ Check for SMS sending errors:"
echo "   pm2 logs --err | grep -iE 'sms|otp|sslwireless' | tail -50"
echo ""
echo "3️⃣ Check phone number format logs:"
echo "   pm2 logs | grep -iE 'phone.*format|userPhone|normalizedPhone|Preparing to send' | tail -50"
echo ""
echo "4️⃣ Check SMS service configuration:"
echo "   pm2 logs | grep -iE 'sslwireless.*configured|isConfigured|SMS service' | tail -30"
echo ""
echo "5️⃣ Check for OTP codes in logs (if SMS failed):"
echo "   pm2 logs | grep -iE 'SMS FAILED|OTP Code|otpCode' | tail -30"
echo ""
echo "6️⃣ Real-time log monitoring:"
echo "   pm2 logs --lines 0 | grep -iE 'otp|sms'"
echo ""
echo "7️⃣ Check recent error logs:"
echo "   pm2 logs --err | tail -100"
echo ""
echo "8️⃣ Check if server restarted recently (deployment indicator):"
echo "   pm2 list"
echo "   pm2 info <app-name> | grep -E 'restart time|uptime'"
echo ""

